export function countries () {
  return [
    { name: 'Afghanistan', abbr: 'af' },
    { name: 'Aland Islands', abbr: 'ax' },
    { name: 'Albania', abbr: 'al' },
    { name: 'Algeria', abbr: 'dz' },
    { name: 'American Samoa', abbr: 'as' },
    { name: 'Andorra', abbr: 'ad' },
    { name: 'Angola', abbr: 'ao' },
    { name: 'Anguilla', abbr: 'ai' },
    { name: 'Antigua and Barbuda', abbr: 'ag' },
    { name: 'Argentina', abbr: 'ar' },
    { name: 'Armenia', abbr: 'am' },
    { name: 'Aruba', abbr: 'aw' },
    { name: 'Australia', abbr: 'au' },
    { name: 'Austria', abbr: 'at' },
    { name: 'Azerbaijan', abbr: 'az' },
    { name: 'Bahamas', abbr: 'bs' },
    { name: 'Bahrain', abbr: 'bh' },
    { name: 'Bangladesh', abbr: 'bd' },
    { name: 'Barbados', abbr: 'bb' },
    { name: 'Belarus', abbr: 'by' },
    { name: 'Belgium', abbr: 'be' },
    { name: 'Belize', abbr: 'bz' },
    { name: 'Benin', abbr: 'bj' },
    { name: 'Bermuda', abbr: 'bm' },
    { name: 'Bhutan', abbr: 'bt' },
    { name: 'Bolivia', abbr: 'bo' },
    { name: 'Bosnia and Herzegovina', abbr: 'ba' },
    { name: 'Botswana', abbr: 'bw' },
    { name: 'Brazil', abbr: 'br' },
    { name: 'British Virgin Islands', abbr: 'vg' },
    { name: 'Brunei', abbr: 'bn' },
    { name: 'Bulgaria', abbr: 'bg' },
    { name: 'Burkina Faso', abbr: 'bf' },
    { name: 'Burundi', abbr: 'bi' },
    { name: 'Cambodia', abbr: 'kh' },
    { name: 'Cameroon', abbr: 'cm' },
    { name: 'Canada', abbr: 'ca' },
    { name: 'Canary Islands', abbr: 'ic' },
    { name: 'Cape Verde', abbr: 'cv' },
    { name: 'Cayman Islands', abbr: 'ky' },
    { name: 'Central African Republic', abbr: 'cf' },
    { name: 'Chad', abbr: 'td' },
    { name: 'Chile', abbr: 'cl' },
    { name: 'China', abbr: 'cn' },
    { name: 'Colombia', abbr: 'co' },
    { name: 'Comoros', abbr: 'km' },
    { name: 'Cook Islands', abbr: 'ck' },
    { name: 'Costa Rica', abbr: 'cr' },
    { name: 'Croatia', abbr: 'hr' },
    { name: 'Cuba', abbr: 'cu' },
    { name: 'Curacao', abbr: 'cw' },
    { name: 'Cyprus', abbr: 'cy' },
    { name: 'Czech Republic', abbr: 'cz' },
    { name: 'Democratic Republic of the Congo', abbr: 'cd' },
    { name: 'Denmark', abbr: 'dk' },
    { name: 'Djibouti', abbr: 'dj' },
    { name: 'Dominica', abbr: 'dm' },
    { name: 'Dominican Republic', abbr: 'do' },
    { name: 'East Timor', abbr: 'tl' },
    { name: 'Ecuador', abbr: 'ec' },
    { name: 'Egypt', abbr: 'eg' },
    { name: 'El Salvador', abbr: 'sv' },
    { name: 'Equatorial Guinea', abbr: 'gq' },
    { name: 'Eritrea', abbr: 'er' },
    { name: 'Estonia', abbr: 'ee' },
    { name: 'Ethiopia', abbr: 'et' },
    { name: 'European Union', abbr: 'eu' },
    { name: 'Falkland Islands', abbr: 'fk' },
    { name: 'Faroe Islands', abbr: 'fo' },
    { name: 'Fiji', abbr: 'fj' },
    { name: 'Finland', abbr: 'fi' },
    { name: 'France', abbr: 'fr' },
    { name: 'French Polynesia', abbr: 'pf' },
    { name: 'French Southern Territories', abbr: 'tf' },
    { name: 'Gabon', abbr: 'ga' },
    { name: 'Gambia', abbr: 'gm' },
    { name: 'Georgia', abbr: 'ge' },
    { name: 'Germany', abbr: 'de' },
    { name: 'Ghana', abbr: 'gh' },
    { name: 'Gibraltar', abbr: 'gi' },
    { name: 'Granada', abbr: 'gd' },
    { name: 'Greece', abbr: 'gr' },
    { name: 'Greenland', abbr: 'gl' },
    { name: 'Guam', abbr: 'gu' },
    { name: 'Guatemala', abbr: 'gt' },
    { name: 'Guernsey', abbr: 'gg' },
    { name: 'Guinea', abbr: 'gn' },
    { name: 'GuineaBissau', abbr: 'gw' },
    { name: 'Guyana', abbr: 'gy' },
    { name: 'Haiti', abbr: 'ht' },
    { name: 'Honduras', abbr: 'hn' },
    { name: 'Hong Kong', abbr: 'hk' },
    { name: 'Hungary', abbr: 'hu' },
    { name: 'Iceland', abbr: 'is' },
    { name: 'India', abbr: 'in' },
    { name: 'Indonesia', abbr: 'id' },
    { name: 'Iran', abbr: 'ir' },
    { name: 'Iraq', abbr: 'iq' },
    { name: 'Ireland', abbr: 'ie' },
    { name: 'Isle of Man', abbr: 'im' },
    { name: 'Israel', abbr: 'il' },
    { name: 'Italy', abbr: 'it' },
    { name: 'Ivory Coast', abbr: 'ci' },
    { name: 'Jamaica', abbr: 'jm' },
    { name: 'Japan', abbr: 'jp' },
    { name: 'Jersey', abbr: 'je' },
    { name: 'Jordan', abbr: 'jo' },
    { name: 'Kazakhstan', abbr: 'kz' },
    { name: 'Kenya', abbr: 'ke' },
    { name: 'Kiribati', abbr: 'ki' },
    { name: 'Kuwait', abbr: 'kw' },
    { name: 'Kyrgyzstan', abbr: 'kg' },
    { name: 'Laos', abbr: 'la' },
    { name: 'Latvia', abbr: 'lv' },
    { name: 'Lebanon', abbr: 'lb' },
    { name: 'Lesotho', abbr: 'ls' },
    { name: 'Liberia', abbr: 'lr' },
    { name: 'Libya', abbr: 'ly' },
    { name: 'Liechtenstein', abbr: 'li' },
    { name: 'Lithuania', abbr: 'lt' },
    { name: 'Luxembourg', abbr: 'lu' },
    { name: 'Macao', abbr: 'mo' },
    { name: 'Madagascar', abbr: 'mg' },
    { name: 'Malawi', abbr: 'mw' },
    { name: 'Malaysia', abbr: 'my' },
    { name: 'Maldives', abbr: 'mv' },
    { name: 'Mali', abbr: 'ml' },
    { name: 'Malta', abbr: 'mt' },
    { name: 'Marshall Islands', abbr: 'mh' },
    { name: 'Martinique', abbr: 'mq' },
    { name: 'Mauritius', abbr: 'mu' },
    { name: 'Mauritania', abbr: 'mr' },
    { name: 'Mayotte', abbr: 'yt' },
    { name: 'Mexico', abbr: 'mx' },
    { name: 'Micronesia', abbr: 'fm' },
    { name: 'Moldova', abbr: 'md' },
    { name: 'Monaco', abbr: 'mc' },
    { name: 'Mongolia', abbr: 'mn' },
    { name: 'Montenegro', abbr: 'me' },
    { name: 'Montserrat', abbr: 'ms' },
    { name: 'Morocco', abbr: 'ma' },
    { name: 'Mozambique', abbr: 'mz' },
    { name: 'Namibia', abbr: 'na' },
    { name: 'Myanmar (Burma)', abbr: 'mm' },
    { name: 'Nauru', abbr: 'nr' },
    { name: 'Nepal', abbr: 'np' },
    { name: 'Netherlands', abbr: 'nl' },
    { name: 'Netherlands Antilles', abbr: 'an' },
    { name: 'New Caledonia', abbr: 'nc' },
    { name: 'New Zealand', abbr: 'nz' },
    { name: 'Nicaragua', abbr: 'ni' },
    { name: 'Niger', abbr: 'ne' },
    { name: 'Nigeria', abbr: 'ng' },
    { name: 'Niue', abbr: 'nu' },
    { name: 'Norfolk Island', abbr: 'nf' },
    { name: 'North Korea', abbr: 'kp' },
    { name: 'North Macedonia', abbr: 'mk' },
    { name: 'Northern Mariana Islands', abbr: 'mp' },
    { name: 'Norway', abbr: 'no' },
    { name: 'Oman', abbr: 'om' },
    { name: 'Pakistan', abbr: 'pk' },
    { name: 'Palau', abbr: 'pw' },
    { name: 'Palestinian Authority', abbr: 'ps' },
    { name: 'Panama', abbr: 'pa' },
    { name: 'Papua New Guinea', abbr: 'pg' },
    { name: 'Paraguay', abbr: 'py' },
    { name: 'Peru', abbr: 'pe' },
    { name: 'Philippines', abbr: 'ph' },
    { name: 'Pitcairn', abbr: 'pn' },
    { name: 'Poland', abbr: 'pl' },
    { name: 'Portugal', abbr: 'pt' },
    { name: 'Puerto Rico', abbr: 'pr' },
    { name: 'Qatar', abbr: 'qa' },
    { name: 'Republic of the Congo', abbr: 'cg' },
    { name: 'Romania', abbr: 'ro' },
    { name: 'Russia', abbr: 'ru' },
    { name: 'Rwanda', abbr: 'rw' },
    { name: 'Saint Barthelemy', abbr: 'bl' },
    { name: 'Saint Helena', abbr: 'sh' },
    { name: 'Saint Kitts and Nevis', abbr: 'kn' },
    { name: 'Saint Lucia', abbr: 'lc' },
    { name: 'Saint Martin', abbr: 'mf' },
    { name: 'Saint Vincent and the Grenadines', abbr: 'vc' },
    { name: 'Samoa', abbr: 'ws' },
    { name: 'San Marino', abbr: 'sm' },
    { name: 'Sao Tome and Principe', abbr: 'st' },
    { name: 'Saudi Arabia', abbr: 'sa' },
    { name: 'Senegal', abbr: 'sn' },
    { name: 'Serbia', abbr: 'rs' },
    { name: 'Seychelles', abbr: 'sc' },
    { name: 'Sierra Leone', abbr: 'sl' },
    { name: 'Singapore', abbr: 'sg' },
    { name: 'Slovakia', abbr: 'sk' },
    { name: 'Slovenia', abbr: 'si' },
    { name: 'Solomon Islands', abbr: 'sb' },
    { name: 'Somalia', abbr: 'so' },
    { name: 'South Africa', abbr: 'za' },
    { name: 'South Korea', abbr: 'kr' },
    { name: 'South Sudan', abbr: 'ss' },
    { name: 'Spain', abbr: 'es' },
    { name: 'Sri Lanka', abbr: 'lk' },
    { name: 'Sudan', abbr: 'sd' },
    { name: 'Suriname', abbr: 'sr' },
    { name: 'Swaziland', abbr: 'sz' },
    { name: 'Sweden', abbr: 'se' },
    { name: 'Switzerland', abbr: 'ch' },
    { name: 'Syria', abbr: 'sy' },
    { name: 'Taiwan', abbr: 'tw' },
    { name: 'Tajikistan', abbr: 'tj' },
    { name: 'Tanzania', abbr: 'tz' },
    { name: 'Thailand', abbr: 'th' },
    { name: 'Togo', abbr: 'tg' },
    { name: 'Tokelau', abbr: 'tk' },
    { name: 'Tonga', abbr: 'to' },
    { name: 'Trinidad and Tobago', abbr: 'tt' },
    { name: 'Tunisia', abbr: 'tn' },
    { name: 'Turkey', abbr: 'tr' },
    { name: 'Turkmenistan', abbr: 'tm' },
    { name: 'Turks and Caicos Islands', abbr: 'tc' },
    { name: 'Tuvalu', abbr: 'tv' },
    { name: 'Uganda', abbr: 'ug' },
    { name: 'Ukraine', abbr: 'ua' },
    { name: 'United Arab Emirates', abbr: 'ae' },
    { name: 'United Kingdom', abbr: 'gb' },
    { name: 'United States', abbr: 'us' },
    { name: 'Uruguay', abbr: 'uy' },
    { name: 'US Virgin Islands', abbr: 'vi' },
    { name: 'Uzbekistan', abbr: 'uz' },
    { name: 'Vanuatu', abbr: 'vu' },
    { name: 'Vatican City', abbr: 'va' },
    { name: 'Venezuela', abbr: 've' },
    { name: 'Vietnam', abbr: 'vn' },
    { name: 'Wallis and Futuna', abbr: 'wf' },
    { name: 'Western Sahara', abbr: 'eh' },
    { name: 'Yemen', abbr: 'ye' },
    { name: 'Zambia', abbr: 'zm' },
    { name: 'Zimbabwe', abbr: 'zw' }
  ]
}
export function usStates () {
  return [
    { name: 'Alabama', abbr: 'AL' },
    { name: 'Alaska', abbr: 'AK' },
    { name: 'Arizona', abbr: 'AZ' },
    { name: 'Arkansas', abbr: 'AR' },
    { name: 'California', abbr: 'CA' },
    { name: 'Colorado', abbr: 'CO' },
    { name: 'Connecticut', abbr: 'CT' },
    { name: 'Delaware', abbr: 'DE' },
    { name: 'District of Columbia', abbr: 'DC' },
    { name: 'Florida', abbr: 'FL' },
    { name: 'Georgia', abbr: 'GA' },
    { name: 'Hawaii', abbr: 'HI' },
    { name: 'Idaho', abbr: 'ID' },
    { name: 'Illinois', abbr: 'IL' },
    { name: 'Indiana', abbr: 'IN' },
    { name: 'Iowa', abbr: 'IA' },
    { name: 'Kansas', abbr: 'KS' },
    { name: 'Kentucky', abbr: 'KY' },
    { name: 'Louisiana', abbr: 'LA' },
    { name: 'Maine', abbr: 'ME' },
    { name: 'Maryland', abbr: 'MD' },
    { name: 'Massachusetts', abbr: 'MA' },
    { name: 'Michigan', abbr: 'MI' },
    { name: 'Minnesota', abbr: 'MN' },
    { name: 'Mississippi', abbr: 'MS' },
    { name: 'Missouri', abbr: 'MO' },
    { name: 'Montana', abbr: 'MT' },
    { name: 'Nebraska', abbr: 'NE' },
    { name: 'Nevada', abbr: 'NV' },
    { name: 'New Hampshire', abbr: 'NH' },
    { name: 'New Jersey', abbr: 'NJ' },
    { name: 'New Mexico', abbr: 'NM' },
    { name: 'New York', abbr: 'NY' },
    { name: 'North Carolina', abbr: 'NC' },
    { name: 'North Dakota', abbr: 'ND' },
    { name: 'Ohio', abbr: 'OH' },
    { name: 'Oklahoma', abbr: 'OK' },
    { name: 'Oregon', abbr: 'OR' },
    { name: 'Pennsylvania', abbr: 'PA' },
    { name: 'Rhode Island', abbr: 'RI' },
    { name: 'South Carolina', abbr: 'SC' },
    { name: 'South Dakota', abbr: 'SD' },
    { name: 'Tennessee', abbr: 'TN' },
    { name: 'Texas', abbr: 'TX' },
    { name: 'Utah', abbr: 'UT' },
    { name: 'Vermont', abbr: 'VT' },
    { name: 'Virginia', abbr: 'VA' },
    { name: 'Washington', abbr: 'WA' },
    { name: 'West Virginia', abbr: 'WV' },
    { name: 'Wisconsin', abbr: 'WI' },
    { name: 'Wyoming', abbr: 'WY' }
  ]
}
export function caProvinces () {
  return [
    { name: 'Alberta', abbr: 'AB' },
    { name: 'British Columbia', abbr: 'BC' },
    { name: 'Manitoba', abbr: 'MB' },
    { name: 'New Brunswick', abbr: 'NB' },
    { name: 'Newfoundland and Labrador', abbr: 'NL' },
    { name: 'Northwest Territories', abbr: 'NT' },
    { name: 'Nova Scotia', abbr: 'NS' },
    { name: 'Nunavut', abbr: 'NU' },
    { name: 'Ontario', abbr: 'ON' },
    { name: 'Prince Edward Island', abbr: 'PE' },
    { name: 'Québec', abbr: 'QC' },
    { name: 'Saskatchewan', abbr: 'SK' },
    { name: 'Yukon', abbr: 'YT' }
  ]
}

export function auStates () {
  return [
    { name: 'Australian Capital Territory', abbr: 'ACT' },
    { name: 'New South Wales', abbr: 'NSW' },
    { name: 'Northern Territory', abbr: 'NT' },
    { name: 'Queensland', abbr: 'QLD' },
    { name: 'South Australia', abbr: 'SA' },
    { name: 'Tasmania', abbr: 'TAS' },
    { name: 'Victoria', abbr: 'VIC' },
    { name: 'Western Australia', abbr: 'WA' }
  ]
}

export function thProvinces () {
  return [
    { name: 'Bangkok', abbr: 'BKK' },
    { name: 'Amnat Charoen', abbr: 'ACR' },
    { name: 'Ang Thong', abbr: 'ATG' },
    { name: 'Bueng Kan', abbr: 'BKN' },
    { name: 'Buriram', abbr: 'BRM' },
    { name: 'Chachoengsao', abbr: 'CCO' },
    { name: 'Chainat', abbr: 'CNT' },
    { name: 'Chaiyaphum', abbr: 'CPM' },
    { name: 'Chanthaburi', abbr: 'CTI' },
    { name: 'Chiang Mai', abbr: 'CMI' },
    { name: 'Chiang Rai', abbr: 'CRI' },
    { name: 'Chonburi', abbr: 'CBI' },
    { name: 'Chumphon', abbr: 'CPN' },
    { name: 'Kalasin', abbr: 'KSN' },
    { name: 'Kamphaeng Phet', abbr: 'KPT' },
    { name: 'Kanchanaburi', abbr: 'KRI' },
    { name: 'Khon Kaen', abbr: 'KKN' },
    { name: 'Krabi', abbr: 'KBI' },
    { name: 'Lampang', abbr: 'LPG' },
    { name: 'Lamphun', abbr: 'LPN' },
    { name: 'Loei', abbr: 'LEI' },
    { name: 'Lopburi', abbr: 'LRI' },
    { name: 'Mae Hong Son', abbr: 'MSN' },
    { name: 'Maha Sarakham', abbr: 'MKM' },
    { name: 'Mukdahan', abbr: 'MDH' },
    { name: 'Nakhon Nayok', abbr: 'NYK' },
    { name: 'Nakhon Pathom', abbr: 'NPT' },
    { name: 'Nakhon Phanom', abbr: 'NPM' },
    { name: 'Nakhon Ratchasima', abbr: 'NMA' },
    { name: 'Nakhon Sawan', abbr: 'NSN' },
    { name: 'Nakhon Si Thammarat', abbr: 'NRT' },
    { name: 'Nan', abbr: 'NAN' },
    { name: 'Narathiwat', abbr: 'NWT' },
    { name: 'Nong Bua Lamphu', abbr: 'NBP' },
    { name: 'Nong Khai', abbr: 'NKI' },
    { name: 'Nonthaburi', abbr: 'NBI' },
    { name: 'Pathum Thani', abbr: 'PTE' },
    { name: 'Pattani', abbr: 'PTN' },
    { name: 'Phang Nga', abbr: 'PNA' },
    { name: 'Phatthalung', abbr: 'PLG' },
    { name: 'Phayao', abbr: 'PYO' },
    { name: 'Phetchabun', abbr: 'PNB' },
    { name: 'Phetchaburi', abbr: 'PBI' },
    { name: 'Phichit', abbr: 'PCT' },
    { name: 'Phitsanulok', abbr: 'PLK' },
    { name: 'Phra Nakhon Si Ayutthaya', abbr: 'AYA' },
    { name: 'Phrae', abbr: 'PRE' },
    { name: 'Phuket', abbr: 'PKT' },
    { name: 'Prachinburi', abbr: 'PRI' },
    { name: 'Prachuap Khiri Khan', abbr: 'PKN' },
    { name: 'Ranong', abbr: 'RNG' },
    { name: 'Ratchaburi', abbr: 'RBR' },
    { name: 'Rayong', abbr: 'RYG' },
    { name: 'Roi Et', abbr: 'RET' },
    { name: 'Sa Kaeo', abbr: 'SKW' },
    { name: 'Sakon Nakhon', abbr: 'SNK' },
    { name: 'Samut Prakan', abbr: 'SPK' },
    { name: 'Samut Sakhon', abbr: 'SKN' },
    { name: 'Samut Songkhram', abbr: 'SKM' },
    { name: 'Saraburi', abbr: 'SRI' },
    { name: 'Satun', abbr: 'STN' },
    { name: 'Sing Buri', abbr: 'SBR' },
    { name: 'Sisaket', abbr: 'SSK' },
    { name: 'Songkhla', abbr: 'SKA' },
    { name: 'Sukhothai', abbr: 'STI' },
    { name: 'Suphan Buri', abbr: 'SPB' },
    { name: 'Surat Thani', abbr: 'SNI' },
    { name: 'Surin', abbr: 'SRN' },
    { name: 'Tak', abbr: 'TAK' },
    { name: 'Trang', abbr: 'TRG' },
    { name: 'Trat', abbr: 'TRT' },
    { name: 'Ubon Ratchathani', abbr: 'UBN' },
    { name: 'Udon Thani', abbr: 'UDN' },
    { name: 'Uthai Thani', abbr: 'UTI' },
    { name: 'Uttaradit', abbr: 'UTD' },
    { name: 'Yala', abbr: 'YLA' },
    { name: 'Yasothon', abbr: 'YST' }
  ]
}

export function ruFedSubjects () {
  return [
    { name: 'Adygea', abbr: 'Adygea' },
    { name: 'Altai Krai', abbr: 'Altai Krai' },
    { name: 'Altai Republic', abbr: 'Altai Republic' },
    { name: 'Amur Oblast', abbr: 'Amur Oblast' },
    { name: 'Arkhangelsk Oblast', abbr: 'Arkhangelsk Oblast' },
    { name: 'Astrakhan Oblast', abbr: 'Astrakhan Oblast' },
    { name: 'Bashkortostan', abbr: 'Bashkortostan' },
    { name: 'Belgorod Oblast', abbr: 'Belgorod Oblast' },
    { name: 'Bryansk Oblast', abbr: 'Bryansk Oblast' },
    { name: 'Buryatia', abbr: 'Buryatia' },
    { name: 'Chechnya', abbr: 'Chechnya' },
    { name: 'Chelyabinsk Oblast', abbr: 'Chelyabinsk Oblast' },
    { name: 'Chukotka Autonomous Okrug', abbr: 'Chukotka Autonomous Okrug' },
    { name: 'Chuvashia', abbr: 'Chuvashia' },
    { name: 'Crimea', abbr: 'Crimea' },
    { name: 'Dagestan', abbr: 'Dagestan' },
    { name: 'Ingushetia', abbr: 'Ingushetia' },
    { name: 'Irkutsk Oblast', abbr: 'Irkutsk Oblast' },
    { name: 'Ivanovo Oblast', abbr: 'Ivanovo Oblast' },
    { name: 'Jewish Autonomous Oblast', abbr: 'Jewish Autonomous Oblast' },
    { name: 'KabardinoBalkaria', abbr: 'KabardinoBalkaria' },
    { name: 'Kaliningrad Oblast', abbr: 'Kaliningrad Oblast' },
    { name: 'Kalmykia', abbr: 'Kalmykia' },
    { name: 'Kaluga Oblast', abbr: 'Kaluga Oblast' },
    { name: 'Kamchatka Krai', abbr: 'Kamchatka Krai' },
    { name: 'KarachayCherkessia', abbr: 'KarachayCherkessia' },
    { name: 'Karelia Republic', abbr: 'Karelia Republic' },
    { name: 'Kemerovo Oblast', abbr: 'Kemerovo Oblast' },
    { name: 'Khabarovsk Krai', abbr: 'Khabarovsk Krai' },
    { name: 'Khakassia', abbr: 'Khakassia' },
    { name: 'KhantyMansi Autonomous Okrug', abbr: 'KhantyMansi Autonomous Okrug' },
    { name: 'Kirov Oblast', abbr: 'Kirov Oblast' },
    { name: 'Komi Republic', abbr: 'Komi Republic' },
    { name: 'Kostroma Oblast', abbr: 'Kostroma Oblast' },
    { name: 'Krasnodar Krai', abbr: 'Krasnodar Krai' },
    { name: 'Krasnoyarsk Krai', abbr: 'Krasnoyarsk Krai' },
    { name: 'Kurgan Oblast', abbr: 'Kurgan Oblast' },
    { name: 'Kursk Oblast', abbr: 'Kursk Oblast' },
    { name: 'Leningrad Oblast', abbr: 'Leningrad Oblast' },
    { name: 'Lipetsk Oblast', abbr: 'Lipetsk Oblast' },
    { name: 'Magadan Oblast', abbr: 'Magadan Oblast' },
    { name: 'Mari El', abbr: 'Mari El' },
    { name: 'Mordovia', abbr: 'Mordovia' },
    { name: 'Moscow Federal City', abbr: 'Moscow Federal City' },
    { name: 'Moscow Oblast', abbr: 'Moscow Oblast' },
    { name: 'Murmansk Oblast', abbr: 'Murmansk Oblast' },
    { name: 'Nenets Autonomous Okrug', abbr: 'Nenets Autonomous Okrug' },
    { name: 'Nizhny Novgorod Oblast', abbr: 'Nizhny Novgorod Oblast' },
    { name: 'North OssetiaAlania', abbr: 'North OssetiaAlania' },
    { name: 'Novgorod Oblast', abbr: 'Novgorod Oblast' },
    { name: 'Novosibirsk Oblast', abbr: 'Novosibirsk Oblast' },
    { name: 'Omsk Oblast', abbr: 'Omsk Oblast' },
    { name: 'Orenburg Oblast', abbr: 'Orenburg Oblast' },
    { name: 'Oryol Oblast', abbr: 'Oryol Oblast' },
    { name: 'Penza Oblast', abbr: 'Penza Oblast' },
    { name: 'Perm Krai', abbr: 'Perm Krai' },
    { name: 'Primorsky Krai', abbr: 'Primorsky Krai' },
    { name: 'Pskov Oblast', abbr: 'Pskov Oblast' },
    { name: 'Rostov Oblast', abbr: 'Rostov Oblast' },
    { name: 'Ryazan Oblast', abbr: 'Ryazan Oblast' },
    { name: 'Saint Petersburg Federal City', abbr: 'Saint Petersburg Federal City' },
    { name: 'Sakhalin Oblast', abbr: 'Sakhalin Oblast' },
    { name: 'Samara Oblast', abbr: 'Samara Oblast' },
    { name: 'Saratov Oblast', abbr: 'Saratov Oblast' },
    { name: 'Sevastopol Federal City', abbr: 'Sevastopol Federal City' },
    { name: 'Smolensk Oblast', abbr: 'Smolensk Oblast' },
    { name: 'Stavropol Krai', abbr: 'Stavropol Krai' },
    { name: 'Sverdlovsk Oblast', abbr: 'Sverdlovsk Oblast' },
    { name: 'Tambov Oblast', abbr: 'Tambov Oblast' },
    { name: 'Tatarstan', abbr: 'Tatarstan' },
    { name: 'Tomsk Oblast', abbr: 'Tomsk Oblast' },
    { name: 'Tula Oblast', abbr: 'Tula Oblast' },
    { name: 'Tuva', abbr: 'Tuva' },
    { name: 'Tver Oblast', abbr: 'Tver Oblast' },
    { name: 'Tyumen Oblast', abbr: 'Tyumen Oblast' },
    { name: 'Udmurtia', abbr: 'Udmurtia' },
    { name: 'Ulyanovsk Oblast', abbr: 'Ulyanovsk Oblast' },
    { name: 'Vladimir Oblast', abbr: 'Vladimir Oblast' },
    { name: 'Volgograd Oblast', abbr: 'Volgograd Oblast' },
    { name: 'Vologda Oblast', abbr: 'Vologda Oblast' },
    { name: 'Voronezh Oblast', abbr: 'Voronezh Oblast' },
    { name: 'Yakutia', abbr: 'Yakutia' },
    { name: 'YamaloNenets Autonomous Okrug', abbr: 'YamaloNenets Autonomous Okrug' },
    { name: 'Yaroslavl Oblast', abbr: 'Yaroslavl Oblast' },
    { name: 'Zabaykalsky Krai', abbr: 'Zabaykalsky Krai' }
  ]
}

export function byRegions () {
  return [
    { name: 'Brest Region', abbr: 'Brest Region' },
    { name: 'Gomel Region', abbr: 'Gomel Region' },
    { name: 'Grodno Region', abbr: 'Grodno Region' },
    { name: 'Mogilev Region', abbr: 'Mogilev Region' },
    { name: 'Minsk Region', abbr: 'Minsk Region' },
    { name: 'Vitebsk Region', abbr: 'Vitebsk Region' }
  ]
}
